[package]
name = "dockurl"
version = "0.1.0"
authors = ["Mike Smith <msmith@techempower.com>"]
edition = "2018"

[dependencies]
curl = "0.4.29"
tar = "0.4.28"
thiserror ="1.0.19"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
strum = "0.18.0"
strum_macros = "0.18.0"
